### ISSUE TITLE
Use the right endpoint in the manifest

### ISSUE THREAD

**Issue by mgarciate** [dappnode/DAppNodePackage-mev-boost#14]
The endpoint in the endpoint url should be `http://mev-boost.mev-boost.dappnode:18550` instead of `http://mev-boost.mev-boost:18550`

<img width="437" alt="image" src="https://user-images.githubusercontent.com/7695193/214116325-d288b9f8-03c5-4aa8-a80f-3c735cb2618c.png">

`"links": {
     "endpoint": "http://mev-boost.mev-boost:18550"
}`

**Comment by pablomendezroyo** [comment]
@mgarciate can you provide a description of the issue please?

**Comment by mgarciate** [comment]
> @mgarciate can you provide a description of the issue please?

Done!
